# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mycount2 <- function(pBigMat, indCase, indControl) {
    .Call('bigsnpr_mycount2', PACKAGE = 'bigsnpr', pBigMat, indCase, indControl)
}

clumping <- function(xpMat, rowInd, colInd, ordInd, remain, sumX, denoX, size, thr) {
    .Call('bigsnpr_clumping', PACKAGE = 'bigsnpr', xpMat, rowInd, colInd, ordInd, remain, sumX, denoX, size, thr)
}

pruning <- function(xpMat, rowInd, colInd, keep, mafX, sumX, denoX, size, thr) {
    .Call('bigsnpr_pruning', PACKAGE = 'bigsnpr', xpMat, rowInd, colInd, keep, mafX, sumX, denoX, size, thr)
}

rawToBigPart <- function(xpMat, source, tab, size, colOffset, n, bsz) {
    invisible(.Call('bigsnpr_rawToBigPart', PACKAGE = 'bigsnpr', xpMat, source, tab, size, colOffset, n, bsz))
}

writebina <- function(filename, xpMat, tab) {
    invisible(.Call('bigsnpr_writebina', PACKAGE = 'bigsnpr', filename, xpMat, tab))
}

