# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mycount2 <- function(pBigMat, indCase, indControl) {
    .Call('bigsnpr_mycount2', PACKAGE = 'bigsnpr', pBigMat, indCase, indControl)
}

wcrossprod <- function(pBigMat, covar, y, z0, w0, tol, maxiter) {
    .Call('bigsnpr_wcrossprod', PACKAGE = 'bigsnpr', pBigMat, covar, y, z0, w0, tol, maxiter)
}

prs2 <- function(pBigMat, odds, indTest, indCol) {
    .Call('bigsnpr_prs2', PACKAGE = 'bigsnpr', pBigMat, odds, indTest, indCol)
}

prs1 <- function(pBigMat, betas, indTest, indCol) {
    .Call('bigsnpr_prs1', PACKAGE = 'bigsnpr', pBigMat, betas, indTest, indCol)
}

clumping <- function(pBigMat, rowInd, colInd, remain, sumX, denoX, size, thr) {
    .Call('bigsnpr_clumping', PACKAGE = 'bigsnpr', pBigMat, rowInd, colInd, remain, sumX, denoX, size, thr)
}

pruning <- function(pBigMat, rowInd, keep, mafX, sumX, denoX, size, thr) {
    .Call('bigsnpr_pruning', PACKAGE = 'bigsnpr', pBigMat, rowInd, keep, mafX, sumX, denoX, size, thr)
}

rawToBigPart <- function(pBigMat, source, tab, size, colOffset, n, bsz) {
    invisible(.Call('bigsnpr_rawToBigPart', PACKAGE = 'bigsnpr', pBigMat, source, tab, size, colOffset, n, bsz))
}

writebina <- function(filename, pBigMat, tab) {
    invisible(.Call('bigsnpr_writebina', PACKAGE = 'bigsnpr', filename, pBigMat, tab))
}

